// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKPYR_40xBvOXb8oPqfZbGzGZRp8fmeo0',
    appId: '1:1097181126220:web:a9faf177be949749eddee9',
    messagingSenderId: '1097181126220',
    projectId: 'flexiflow-9be51',
    authDomain: 'flexiflow-9be51.firebaseapp.com',
    storageBucket: 'flexiflow-9be51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhdPCGldn2rEk6hmvSHuS2V4tY1l9o0w',
    appId: '1:1097181126220:android:3ccb9d4239b86915eddee9',
    messagingSenderId: '1097181126220',
    projectId: 'flexiflow-9be51',
    storageBucket: 'flexiflow-9be51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFf1MwF3v7lArzlai8qKyAbH7cbXmzAoI',
    appId: '1:1097181126220:ios:d8be77304d205c79eddee9',
    messagingSenderId: '1097181126220',
    projectId: 'flexiflow-9be51',
    storageBucket: 'flexiflow-9be51.firebasestorage.app',
    iosBundleId: 'com.example.flexiFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFf1MwF3v7lArzlai8qKyAbH7cbXmzAoI',
    appId: '1:1097181126220:ios:d8be77304d205c79eddee9',
    messagingSenderId: '1097181126220',
    projectId: 'flexiflow-9be51',
    storageBucket: 'flexiflow-9be51.firebasestorage.app',
    iosBundleId: 'com.example.flexiFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKPYR_40xBvOXb8oPqfZbGzGZRp8fmeo0',
    appId: '1:1097181126220:web:f4883d5f256fa49feddee9',
    messagingSenderId: '1097181126220',
    projectId: 'flexiflow-9be51',
    authDomain: 'flexiflow-9be51.firebaseapp.com',
    storageBucket: 'flexiflow-9be51.firebasestorage.app',
  );
}
